Improve Panda arm/hand collision model and filters
RobotLocomotion/models pull request #71
Opened 2024-12-15 20:04 UTC by calderpg-tri

2024-12-15 23:52 UTC, calderpg-tri commented
Changes to the Panda collision model(s) and collision filtering, specifically:
1. Adds the additional collision spheres which we have been adding in-code to match the internal self-collision model to the URDF itself as two "extra" links attached to links 2 and 5.
2. Adjusts the collision filtering, particularly around the wrist assembly, so that collisions with the outboard end of link 5 are filtered while collisions with the inboard "extra" on link 5 are not.

See Anzu#15069 for accompanying internal code changes.

2024-12-15 23:54 UTC, calderpg-tri commented
+@jwnimmer-tri for review or delegation, thanks!

cc @abeaulieu-tri @rcory

2024-12-15 23:56 UTC, calderpg-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/71)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @calderpg-tri and @jwnimmer-tri)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/71#-OEBk50QDRiEiJqr2rae:-OEBk50REclq5A0DiMwe:b-6yu490) (no related file):*
working This should not land until Anzu CI has run against it.


<!-- Sent from Reviewable.io -->

2024-12-16 00:06 UTC, jwnimmer-tri reviewed
BTW I can review the change for suitability w.r.t. Drake, but I assume your objective here is to fix something in Anzu for the platform team, which I can't speak for -- if you want Anzu-relevant review to happen here, you'll need to add an additional reviewer for that perspective.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/71#-:-OEBlVfa6g0G6KrSSW21:b-5dry7p)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @calderpg-tri)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/71#-OEBk3oT52T2eb7YQgUS:-OEBk3oT52T2eb7YQgUT:b-sa0hvc) (no related file):*
Are these changes appropriate for use by simulation?  For simulation, collision filters are helpful when the proximity geometry (or less often, joint kinematics) are modeled imprecisely and so would have false positives (i.e., nonsense physics) while computing contact forces.

The phrase "internal self-collision model" above makes me wonder if at least part (1) of this change might be specific to a plant used for control or planning (i.e., a collision avoidance model), instead of a simulation model.

(We do have the ability to use xacro codegen in `drake_models`, in case that's helpful.)


<!-- Sent from Reviewable.io -->

2024-12-16 00:37 UTC, calderpg-tri reviewed
+@abeaulieu-tri for review as platform representative
+@rcory for review as sim representative

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/71#-:-OEBt8-U87l_lUoX4lVI:bfcoe9z)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee abeaulieu-tri, LGTM missing from assignee rcory, platform LGTM missing (waiting on @abeaulieu-tri, @jwnimmer-tri, and @rcory)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/71#-OEBk3oT52T2eb7YQgUS:-OEBnKBr6gdr8z4aPMIc:bss24pl) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Are these changes appropriate for use by simulation?  For simulation, collision filters are helpful when the proximity geometry (or less often, joint kinematics) are modeled imprecisely and so would have false positives (i.e., nonsense physics) while computing contact forces.

The phrase "internal self-collision model" above makes me wonder if at least part (1) of this change might be specific to a plant used for control or planning (i.e., a collision avoidance model), instead of a simulation model.

(We do have the ability to use xacro codegen in `drake_models`, in case that's helpful.)
</blockquote></details>

The "internal self-collision model" is that of the Franka control box itself, which faults on violations of its internal self-collision model (the geometry of which, to the best of our knowledge, is completely undocumented). Obviously it is most important that these changes are used by planner(s)/controller(s) so that the robot is never commanded into the problematic configurations in the first place.

I'm not opposed to having separate sim and planning versions of the Panda models, but I would argue that the change in sim behavior that results from these changes doesn't matter that much, since the configurations affected are those that are effectively unreachable on the real hardware anyways. If anyone is depending on sim behavior there, it will never make a sim->real transition.

In terms of the filters, the within-arm filters are necessary for both planning/control and simulation, since the `extra` links must be manually filtered as they are not automatically filtered as being kinematically adjacent. Hand filters are included for consistency, and practically speaking, and on the as-built hand with factory fingers, collisions between the fingers are impossible as the contacting configuration is the zero limit once the hand has initialized. (Also, I suspect basically no one is using the supplied fingers used in these models at all.)


<!-- Sent from Reviewable.io -->

2024-12-17 16:04 UTC, jwnimmer-tri reviewed
I am going to let the other reviewers take the first pass.  I imagine by the point it circles back to me I'll just platform-review stamp it too and we can merge.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/71#-:-OEKLgzF59nzaeWqqHg-:bc4ssvu)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee abeaulieu-tri, LGTM missing from assignee rcory, platform LGTM missing (waiting on @abeaulieu-tri, @calderpg-tri, and @rcory)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/71#-OEBk3oT52T2eb7YQgUS:-OEKLbhGABRP4aNX7EYF:b-baao30) (no related file):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

The "internal self-collision model" is that of the Franka control box itself, which faults on violations of its internal self-collision model (the geometry of which, to the best of our knowledge, is completely undocumented). Obviously it is most important that these changes are used by planner(s)/controller(s) so that the robot is never commanded into the problematic configurations in the first place.

I'm not opposed to having separate sim and planning versions of the Panda models, but I would argue that the change in sim behavior that results from these changes doesn't matter that much, since the configurations affected are those that are effectively unreachable on the real hardware anyways. If anyone is depending on sim behavior there, it will never make a sim->real transition.

In terms of the filters, the within-arm filters are necessary for both planning/control and simulation, since the `extra` links must be manually filtered as they are not automatically filtered as being kinematically adjacent. Hand filters are included for consistency, and practically speaking, and on the as-built hand with factory fingers, collisions between the fingers are impossible as the contacting configuration is the zero limit once the hand has initialized. (Also, I suspect basically no one is using the supplied fingers used in these models at all.)
</blockquote></details>

I will give it some more thought to be sure, but that all sounds basically reasonable.
___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/71#-OEKLpJz0LEnnD1-Dn-p:-OEKLpJz0LEnnD1-Dn-q:b-gq3l1i) (no related file):*
The URDF files and the README need _lots_ more comments, so that is crystal clear to future readers (1) _how_ our URDF diverge from the upstream URDS and (2) _why_ we've done that.  Basically all of the expository text in the prior thread needs to appear in git, not reviewable.  Probably both with inline comments in the URDFs, and some reminder in the README.


<!-- Sent from Reviewable.io -->

2024-12-17 22:03 UTC, rcory requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/71)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee abeaulieu-tri, LGTM missing from assignee rcory, platform LGTM missing (waiting on @abeaulieu-tri, @calderpg-tri, and @jwnimmer-tri)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/71#-OELarFBAMKAUT9vSEmu:-OELarFC9sIy2V_cZ6G-:b656ugg) (no related file):*
So we are clear on what the changes actually look like, I'm including some snapshots of the before & after collision geometries below. 

My main concern is that these new collision geometries are grossly mismatched with the actual robot body. Perhaps that is ok for self-collision issues, but what about external contact with other items in the scene (e.g., manipulands, or a second arm)? These collision just seem too far off reality from a physics/contact standpoint.

I'm inclined to advocate that these changes instead go into the planning/control model, rather than the physical simulation model.

@dmcconachie-tri and @siyuanfeng-tri What are your thoughts?

For reference, here are the proposed new collision geometries:

![Screenshot from 2024-12-17 13-51-52.png](https://files.reviewableusercontent.io/images/reviewable/6761349/eqUOkko7KKV94XzRY_IoY-mx/Screenshot%20from%202024-12-17%2013-51-52.png)

All collisions shown, before this change:

![Screenshot from 2024-12-17 13-51-24.png](https://files.reviewableusercontent.io/images/reviewable/6761349/SgIUkE3mOUp6Gfst-XJi7ZCv/Screenshot%20from%202024-12-17%2013-51-24.png)

All collisions shown, after this change:

![Screenshot from 2024-12-17 13-51-34.png](https://files.reviewableusercontent.io/images/reviewable/6761349/c7Ljhz_JDQmeCKMYMi7RYD0R/Screenshot%20from%202024-12-17%2013-51-34.png)


<!-- Sent from Reviewable.io -->

2024-12-18 03:11 UTC, siyuanfeng-tri commented
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

So we are clear on what the changes actually look like, I'm including some snapshots of the before & after collision geometries below. 

My main concern is that these new collision geometries are grossly mismatched with the actual robot body. Perhaps that is ok for self-collision issues, but what about external contact with other items in the scene (e.g., manipulands, or a second arm)? These collision just seem too far off reality from a physics/contact standpoint.

I'm inclined to advocate that these changes instead go into the planning/control model, rather than the physical simulation model.

@dmcconachie-tri and @siyuanfeng-tri What are your thoughts?

For reference, here are the proposed new collision geometries:

![Screenshot from 2024-12-17 13-51-52.png](https://files.reviewableusercontent.io/images/reviewable/6761349/eqUOkko7KKV94XzRY_IoY-mx/Screenshot%20from%202024-12-17%2013-51-52.png)

All collisions shown, before this change:

![Screenshot from 2024-12-17 13-51-24.png](https://files.reviewableusercontent.io/images/reviewable/6761349/SgIUkE3mOUp6Gfst-XJi7ZCv/Screenshot%20from%202024-12-17%2013-51-24.png)

All collisions shown, after this change:

![Screenshot from 2024-12-17 13-51-34.png](https://files.reviewableusercontent.io/images/reviewable/6761349/c7Ljhz_JDQmeCKMYMi7RYD0R/Screenshot%20from%202024-12-17%2013-51-34.png)
</blockquote></details>

waiiiiiiiiiit. i thought calder is just touching the planning models.. def no to sim with rick's above visualization. 


<!-- Sent from Reviewable.io -->

2025-01-23 16:41 UTC, jwnimmer-tri commented
Subsumed by #74.

2025-01-23 16:41 UTC, closed without merging